
appName: "be-argocd"

replicaCount: 1

image:
  tag: "411c18a32fd053c7e3b445d0d8ec85aa5e00a36d"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "debug"
  DEBUG_MODE: "true"
