
appName: "be-argocd"

replicaCount: 1

image:
  tag: "460ff98bf6f6d2a4ef327b15e2e3301082a87f93"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "debug"
  DEBUG_MODE: "true"
