
appName: "be-argocd"

replicaCount: 1

image:
  tag: "cb7a0d8a9adcd45a21be9467f16466f726eeda18"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "debug"
  DEBUG_MODE: "true"
