apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tf1-rollouts
  namespace: argocd
  annotations:
    # Cài đặt ở Wave 0, cùng lúc với Foundation và Gatekeeper
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: tf1-project
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.37.2
    chart: argo-rollouts
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
