apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tf1-project
  namespace: argocd
spec:
  description: Project for TF1 Triage Hub Application
  

  sourceRepos:
    - "https://github.com/NguyenKhanhDuy2703/practic_eks_argorcd_aws.git"
    - "https://open-policy-agent.github.io/gatekeeper/charts"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://argoproj.github.io/argo-helm"
    - "https://charts.external-secrets.io"
  

  destinations:
    - namespace: "tf1-sandbox"
      server: https://kubernetes.default.svc
    - namespace: "kube-system"
      server: https://kubernetes.default.svc
    - namespace: "gatekeeper-system"
      server: https://kubernetes.default.svc
    - namespace: "monitoring"
      server: https://kubernetes.default.svc
    - namespace: "argo-rollouts"
      server: https://kubernetes.default.svc
    - namespace: "external-secrets"
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
