

appName: "backend"

replicaCount: 1

image:
  repository: ghcr.io/nguyenkhanhduy2703/practic_eks_argorcd_aws
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  ENVIRONMENT: "default"
  LOG_LEVEL: "info"
