
appName: "be-argocd"

replicaCount: 1

image:
  tag: "f17768faaf242457fc68f128d3bad9096105f925"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

env:
  ENVIRONMENT: "sandbox"
  LOG_LEVEL: "debug"
  DEBUG_MODE: "true"
